site_name: Space Radiation & Material
site_description: Information about space radiation and its effect on matter
site_author: SimoneR85

theme:
 name: material
 language:en
 palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Passa alla modalità scura
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Passa alla modalità chiara
  features:
    - navigation.indexes
    - navigation.instant
    - search.suggest
    - search.highlight

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences
  - pymdownx.details
  - admonition

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
